[package]
name = "cosmic-applet-toggle-keyboard"
version = "0.1.0"
edition = "2024"

[dependencies]
libcosmic = { git = "https://github.com/pop-os/libcosmic", features = ["applet", "tokio", "wayland"] }
tracing = "0.1"
tracing-subscriber = "0.3"
